WIDTH, HEIGHT = 1000, 500
BOARD_WIDTH, BOARD_HEIGHT = 500, 500
PIECE_WIDTH, PIECE_HEIGHT = 50, 50
BOARD_START_W, BOARD_START_H = 25, 25
ROW_GAP, COL_GAP = 50, 50

KEY_BLACK_PLAYER = "black_player"
KEY_WHITE_PLAYER = "white_player"
KEY_TOTAL_MOVE = "total_move"
KEY_MATCH_RESULT = "match_result"